const mongoose = require('mongoose');

const archivedMemberSchema = new mongoose.Schema({
  hostelId: { type: mongoose.Schema.Types.ObjectId, ref: 'Hostel', index: true },
  originalId: String,
  memberId: String,
  memberIdNumber: Number,
  name: String,
  mobileNo: String,
  fathersName: String,
  fathersMobileNo: String,
  aadharNumber: String,
  fathersOccupation: String,
  studentOccupation: String,
  admissionDate: Date,
  permanentAddress: String,
  localRelativeName: String,
  localRelativeAddress: String,
  localRelativeMobile: String,
  permanentAddressRelativeName: String,
  permanentAddressRelativeAddress: String,
  permanentAddressRelativeMobile: String,
  photoUrl: String,
  roomNumber: Number,
  numberOfMembers: Number,
  rent: Number,
  advance: Number,
  roomJoinDate: Date,
  roomLeavingDate: Date,
  policeFormVerified: Boolean,
  registrationYear: String,
  vacatedOn: Date,
  vacatedReason: String,
  originalCreatedAt: Date,
  isActive: { type: Boolean, default: false },
}, { timestamps: true });

module.exports = mongoose.model('ArchivedMember', archivedMemberSchema);
